LowpanException: Refactor exception handling
Got rid of the exposed exception code and we now rely on subclasses of
LowpanException. Also introduces a new exception: LowpanRuntimeException

LowpanRuntimeException, as a subclass of AndroidRuntimeException,
doesn't need explicitly delared "throws" statements for function
declarations. Most Exceptions are still LowpanExceptions, but some
specific error codes, such as ERROR_NCP_PROBLEM, are now using this
new exception class.

Bug: b/63708181
Change-Id: Idba6233ac4803d33561b5aa951c8fa846c3ab1d8